name: Automatically submit the 2019-nCoV report sheet of BUPT

on:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      - name: Run Script
        run: |
          yarn run ts-node src/index.ts
        env:
          BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
          BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          NTBA_FIX_319: 1
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          QQ: ${{ secrets.QQ }}
          QQBOT_SEND_MSG_API: ${{ secrets.QQBOT_SEND_MSG_API }}
